plugins {
    id 'com.gradleup.shadow' version '9.4.1'
    id 'java'
}

group 'net.tyrannys'
version '1.1'
jar.enabled = false

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:26.1-R0.1-SNAPSHOT'
    implementation 'org.bstats:bstats-bukkit:3.2.1'
}

def targetJavaVersion = 25
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    filter { String line -> line.replace('${version}', project.version.toString()) }
}

shadowJar {
    archiveFileName = 'RottenFlesh2Leather-' + project.version.toString() + '.jar'
    relocate 'org.bstats', 'net.tyrannys.rottenflesh2leather.lib.bstats'
}

artifacts {
    shadowJar
}

assemble.dependsOn(shadowJar)
