<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>net.tyrannys</groupId>
    <version>${project.parent.version}</version>
    <artifactId>RottenFlesh2Leather-dist</artifactId>
    <packaging>jar</packaging>
    <parent>
        <groupId>net.tyrannys</groupId>
        <artifactId>RottenFlesh2Leather</artifactId>
        <version>1.0</version>
    </parent>
    <build>
        <directory>../target</directory>
        <finalName>RottenFlesh2Leather-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>net.tyrannys.RottenFlesh2Leather-*</include>
                                </includes>
                            </artifactSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>net.tyrannys</groupId>
            <artifactId>RottenFlesh2Leather-core</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>net.tyrannys</groupId>
            <artifactId>RottenFlesh2Leather-1_20_R2</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>


</project>